var intro=[
	{
		e:'左侧为可搜索表格组件，组件参数为表头信息，表格信息。用户可以通过输入关键字进行筛选对应的表格行',
		h:'&lt;selecttb :ths="tableHead" :tbdatas="tableData" :tdnames="tableName"&gt;&lt;selecttb&gt;',
		c:'css',
		j:'js'
	},
	{
		e:'左侧为弹窗组件，可通过三个slot插槽注入弹窗头部，主体和尾部信息，从而实现提示、警告、选择等弹窗信息，同时可通过绑定shows属性绑定弹窗的隐藏和显示.',
		h:'<>',
		c:'css',
		j:'js'
	},
	{
		e:'左侧为可增删改查的表格组件,该组件实现了表格数据的增加、修改、查寻和删除，通过修改组件过滤设置数据格式，修改数据源即可实现常见页面table数据，',
		h:'<curd>',
		c:'css',
		j:'js'
	},
	{
		e:'这是一个轮播图',
		h:'<>',
		c:'css',
		j:'js'
	},
	{
		e:'使用vue-router模拟手机app操作切换页面效果',
		h:'<>',
		c:'css',
		j:'js'
	}
]